// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device.proto

#ifndef PROTOBUF_INCLUDED_device_2eproto
#define PROTOBUF_INCLUDED_device_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_device_2eproto 

namespace protobuf_device_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[10];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_device_2eproto
namespace device_service {
class DeviceInfoDetail;
class DeviceInfoDetailDefaultTypeInternal;
extern DeviceInfoDetailDefaultTypeInternal _DeviceInfoDetail_default_instance_;
class DeviceInfoRequest;
class DeviceInfoRequestDefaultTypeInternal;
extern DeviceInfoRequestDefaultTypeInternal _DeviceInfoRequest_default_instance_;
class DeviceInfoResponse;
class DeviceInfoResponseDefaultTypeInternal;
extern DeviceInfoResponseDefaultTypeInternal _DeviceInfoResponse_default_instance_;
class DeviceNameListRequest;
class DeviceNameListRequestDefaultTypeInternal;
extern DeviceNameListRequestDefaultTypeInternal _DeviceNameListRequest_default_instance_;
class DeviceNameListResponse;
class DeviceNameListResponseDefaultTypeInternal;
extern DeviceNameListResponseDefaultTypeInternal _DeviceNameListResponse_default_instance_;
class DeviceSlaveCntRequest;
class DeviceSlaveCntRequestDefaultTypeInternal;
extern DeviceSlaveCntRequestDefaultTypeInternal _DeviceSlaveCntRequest_default_instance_;
class DeviceSlaveCntResponse;
class DeviceSlaveCntResponseDefaultTypeInternal;
extern DeviceSlaveCntResponseDefaultTypeInternal _DeviceSlaveCntResponse_default_instance_;
class DeviceTableBySlaveIdRequest;
class DeviceTableBySlaveIdRequestDefaultTypeInternal;
extern DeviceTableBySlaveIdRequestDefaultTypeInternal _DeviceTableBySlaveIdRequest_default_instance_;
class DeviceTableBySlaveIdResponse;
class DeviceTableBySlaveIdResponseDefaultTypeInternal;
extern DeviceTableBySlaveIdResponseDefaultTypeInternal _DeviceTableBySlaveIdResponse_default_instance_;
class DeviceTableRow;
class DeviceTableRowDefaultTypeInternal;
extern DeviceTableRowDefaultTypeInternal _DeviceTableRow_default_instance_;
}  // namespace device_service
namespace google {
namespace protobuf {
template<> ::device_service::DeviceInfoDetail* Arena::CreateMaybeMessage<::device_service::DeviceInfoDetail>(Arena*);
template<> ::device_service::DeviceInfoRequest* Arena::CreateMaybeMessage<::device_service::DeviceInfoRequest>(Arena*);
template<> ::device_service::DeviceInfoResponse* Arena::CreateMaybeMessage<::device_service::DeviceInfoResponse>(Arena*);
template<> ::device_service::DeviceNameListRequest* Arena::CreateMaybeMessage<::device_service::DeviceNameListRequest>(Arena*);
template<> ::device_service::DeviceNameListResponse* Arena::CreateMaybeMessage<::device_service::DeviceNameListResponse>(Arena*);
template<> ::device_service::DeviceSlaveCntRequest* Arena::CreateMaybeMessage<::device_service::DeviceSlaveCntRequest>(Arena*);
template<> ::device_service::DeviceSlaveCntResponse* Arena::CreateMaybeMessage<::device_service::DeviceSlaveCntResponse>(Arena*);
template<> ::device_service::DeviceTableBySlaveIdRequest* Arena::CreateMaybeMessage<::device_service::DeviceTableBySlaveIdRequest>(Arena*);
template<> ::device_service::DeviceTableBySlaveIdResponse* Arena::CreateMaybeMessage<::device_service::DeviceTableBySlaveIdResponse>(Arena*);
template<> ::device_service::DeviceTableRow* Arena::CreateMaybeMessage<::device_service::DeviceTableRow>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace device_service {

// ===================================================================

class DeviceNameListRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:device_service.DeviceNameListRequest) */ {
 public:
  DeviceNameListRequest();
  virtual ~DeviceNameListRequest();

  DeviceNameListRequest(const DeviceNameListRequest& from);

  inline DeviceNameListRequest& operator=(const DeviceNameListRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeviceNameListRequest(DeviceNameListRequest&& from) noexcept
    : DeviceNameListRequest() {
    *this = ::std::move(from);
  }

  inline DeviceNameListRequest& operator=(DeviceNameListRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeviceNameListRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeviceNameListRequest* internal_default_instance() {
    return reinterpret_cast<const DeviceNameListRequest*>(
               &_DeviceNameListRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(DeviceNameListRequest* other);
  friend void swap(DeviceNameListRequest& a, DeviceNameListRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeviceNameListRequest* New() const final {
    return CreateMaybeMessage<DeviceNameListRequest>(NULL);
  }

  DeviceNameListRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeviceNameListRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DeviceNameListRequest& from);
  void MergeFrom(const DeviceNameListRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeviceNameListRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string device_name = 1;
  void clear_device_name();
  static const int kDeviceNameFieldNumber = 1;
  const ::std::string& device_name() const;
  void set_device_name(const ::std::string& value);
  #if LANG_CXX11
  void set_device_name(::std::string&& value);
  #endif
  void set_device_name(const char* value);
  void set_device_name(const char* value, size_t size);
  ::std::string* mutable_device_name();
  ::std::string* release_device_name();
  void set_allocated_device_name(::std::string* device_name);

  // @@protoc_insertion_point(class_scope:device_service.DeviceNameListRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr device_name_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_device_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeviceNameListResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:device_service.DeviceNameListResponse) */ {
 public:
  DeviceNameListResponse();
  virtual ~DeviceNameListResponse();

  DeviceNameListResponse(const DeviceNameListResponse& from);

  inline DeviceNameListResponse& operator=(const DeviceNameListResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeviceNameListResponse(DeviceNameListResponse&& from) noexcept
    : DeviceNameListResponse() {
    *this = ::std::move(from);
  }

  inline DeviceNameListResponse& operator=(DeviceNameListResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeviceNameListResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeviceNameListResponse* internal_default_instance() {
    return reinterpret_cast<const DeviceNameListResponse*>(
               &_DeviceNameListResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(DeviceNameListResponse* other);
  friend void swap(DeviceNameListResponse& a, DeviceNameListResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeviceNameListResponse* New() const final {
    return CreateMaybeMessage<DeviceNameListResponse>(NULL);
  }

  DeviceNameListResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeviceNameListResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DeviceNameListResponse& from);
  void MergeFrom(const DeviceNameListResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeviceNameListResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string device_names = 1;
  int device_names_size() const;
  void clear_device_names();
  static const int kDeviceNamesFieldNumber = 1;
  const ::std::string& device_names(int index) const;
  ::std::string* mutable_device_names(int index);
  void set_device_names(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_device_names(int index, ::std::string&& value);
  #endif
  void set_device_names(int index, const char* value);
  void set_device_names(int index, const char* value, size_t size);
  ::std::string* add_device_names();
  void add_device_names(const ::std::string& value);
  #if LANG_CXX11
  void add_device_names(::std::string&& value);
  #endif
  void add_device_names(const char* value);
  void add_device_names(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& device_names() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_device_names();

  // @@protoc_insertion_point(class_scope:device_service.DeviceNameListResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> device_names_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_device_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeviceSlaveCntRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:device_service.DeviceSlaveCntRequest) */ {
 public:
  DeviceSlaveCntRequest();
  virtual ~DeviceSlaveCntRequest();

  DeviceSlaveCntRequest(const DeviceSlaveCntRequest& from);

  inline DeviceSlaveCntRequest& operator=(const DeviceSlaveCntRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeviceSlaveCntRequest(DeviceSlaveCntRequest&& from) noexcept
    : DeviceSlaveCntRequest() {
    *this = ::std::move(from);
  }

  inline DeviceSlaveCntRequest& operator=(DeviceSlaveCntRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeviceSlaveCntRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeviceSlaveCntRequest* internal_default_instance() {
    return reinterpret_cast<const DeviceSlaveCntRequest*>(
               &_DeviceSlaveCntRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(DeviceSlaveCntRequest* other);
  friend void swap(DeviceSlaveCntRequest& a, DeviceSlaveCntRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeviceSlaveCntRequest* New() const final {
    return CreateMaybeMessage<DeviceSlaveCntRequest>(NULL);
  }

  DeviceSlaveCntRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeviceSlaveCntRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DeviceSlaveCntRequest& from);
  void MergeFrom(const DeviceSlaveCntRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeviceSlaveCntRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string device_name = 1;
  void clear_device_name();
  static const int kDeviceNameFieldNumber = 1;
  const ::std::string& device_name() const;
  void set_device_name(const ::std::string& value);
  #if LANG_CXX11
  void set_device_name(::std::string&& value);
  #endif
  void set_device_name(const char* value);
  void set_device_name(const char* value, size_t size);
  ::std::string* mutable_device_name();
  ::std::string* release_device_name();
  void set_allocated_device_name(::std::string* device_name);

  // @@protoc_insertion_point(class_scope:device_service.DeviceSlaveCntRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr device_name_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_device_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeviceSlaveCntResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:device_service.DeviceSlaveCntResponse) */ {
 public:
  DeviceSlaveCntResponse();
  virtual ~DeviceSlaveCntResponse();

  DeviceSlaveCntResponse(const DeviceSlaveCntResponse& from);

  inline DeviceSlaveCntResponse& operator=(const DeviceSlaveCntResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeviceSlaveCntResponse(DeviceSlaveCntResponse&& from) noexcept
    : DeviceSlaveCntResponse() {
    *this = ::std::move(from);
  }

  inline DeviceSlaveCntResponse& operator=(DeviceSlaveCntResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeviceSlaveCntResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeviceSlaveCntResponse* internal_default_instance() {
    return reinterpret_cast<const DeviceSlaveCntResponse*>(
               &_DeviceSlaveCntResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(DeviceSlaveCntResponse* other);
  friend void swap(DeviceSlaveCntResponse& a, DeviceSlaveCntResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeviceSlaveCntResponse* New() const final {
    return CreateMaybeMessage<DeviceSlaveCntResponse>(NULL);
  }

  DeviceSlaveCntResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeviceSlaveCntResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DeviceSlaveCntResponse& from);
  void MergeFrom(const DeviceSlaveCntResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeviceSlaveCntResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 slave_cnt = 1;
  void clear_slave_cnt();
  static const int kSlaveCntFieldNumber = 1;
  ::google::protobuf::int32 slave_cnt() const;
  void set_slave_cnt(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:device_service.DeviceSlaveCntResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 slave_cnt_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_device_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeviceInfoDetail : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:device_service.DeviceInfoDetail) */ {
 public:
  DeviceInfoDetail();
  virtual ~DeviceInfoDetail();

  DeviceInfoDetail(const DeviceInfoDetail& from);

  inline DeviceInfoDetail& operator=(const DeviceInfoDetail& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeviceInfoDetail(DeviceInfoDetail&& from) noexcept
    : DeviceInfoDetail() {
    *this = ::std::move(from);
  }

  inline DeviceInfoDetail& operator=(DeviceInfoDetail&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeviceInfoDetail& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeviceInfoDetail* internal_default_instance() {
    return reinterpret_cast<const DeviceInfoDetail*>(
               &_DeviceInfoDetail_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(DeviceInfoDetail* other);
  friend void swap(DeviceInfoDetail& a, DeviceInfoDetail& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeviceInfoDetail* New() const final {
    return CreateMaybeMessage<DeviceInfoDetail>(NULL);
  }

  DeviceInfoDetail* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeviceInfoDetail>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DeviceInfoDetail& from);
  void MergeFrom(const DeviceInfoDetail& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeviceInfoDetail* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string ip = 1;
  void clear_ip();
  static const int kIpFieldNumber = 1;
  const ::std::string& ip() const;
  void set_ip(const ::std::string& value);
  #if LANG_CXX11
  void set_ip(::std::string&& value);
  #endif
  void set_ip(const char* value);
  void set_ip(const char* value, size_t size);
  ::std::string* mutable_ip();
  ::std::string* release_ip();
  void set_allocated_ip(::std::string* ip);

  // string type = 3;
  void clear_type();
  static const int kTypeFieldNumber = 3;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  #if LANG_CXX11
  void set_type(::std::string&& value);
  #endif
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // int32 port = 2;
  void clear_port();
  static const int kPortFieldNumber = 2;
  ::google::protobuf::int32 port() const;
  void set_port(::google::protobuf::int32 value);

  // bool server_status = 4;
  void clear_server_status();
  static const int kServerStatusFieldNumber = 4;
  bool server_status() const;
  void set_server_status(bool value);

  // bool simulate_status = 5;
  void clear_simulate_status();
  static const int kSimulateStatusFieldNumber = 5;
  bool simulate_status() const;
  void set_simulate_status(bool value);

  // bool plan_status = 6;
  void clear_plan_status();
  static const int kPlanStatusFieldNumber = 6;
  bool plan_status() const;
  void set_plan_status(bool value);

  // @@protoc_insertion_point(class_scope:device_service.DeviceInfoDetail)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr ip_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  ::google::protobuf::int32 port_;
  bool server_status_;
  bool simulate_status_;
  bool plan_status_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_device_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeviceInfoRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:device_service.DeviceInfoRequest) */ {
 public:
  DeviceInfoRequest();
  virtual ~DeviceInfoRequest();

  DeviceInfoRequest(const DeviceInfoRequest& from);

  inline DeviceInfoRequest& operator=(const DeviceInfoRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeviceInfoRequest(DeviceInfoRequest&& from) noexcept
    : DeviceInfoRequest() {
    *this = ::std::move(from);
  }

  inline DeviceInfoRequest& operator=(DeviceInfoRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeviceInfoRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeviceInfoRequest* internal_default_instance() {
    return reinterpret_cast<const DeviceInfoRequest*>(
               &_DeviceInfoRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(DeviceInfoRequest* other);
  friend void swap(DeviceInfoRequest& a, DeviceInfoRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeviceInfoRequest* New() const final {
    return CreateMaybeMessage<DeviceInfoRequest>(NULL);
  }

  DeviceInfoRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeviceInfoRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DeviceInfoRequest& from);
  void MergeFrom(const DeviceInfoRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeviceInfoRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string device_name = 1;
  void clear_device_name();
  static const int kDeviceNameFieldNumber = 1;
  const ::std::string& device_name() const;
  void set_device_name(const ::std::string& value);
  #if LANG_CXX11
  void set_device_name(::std::string&& value);
  #endif
  void set_device_name(const char* value);
  void set_device_name(const char* value, size_t size);
  ::std::string* mutable_device_name();
  ::std::string* release_device_name();
  void set_allocated_device_name(::std::string* device_name);

  // @@protoc_insertion_point(class_scope:device_service.DeviceInfoRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr device_name_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_device_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeviceInfoResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:device_service.DeviceInfoResponse) */ {
 public:
  DeviceInfoResponse();
  virtual ~DeviceInfoResponse();

  DeviceInfoResponse(const DeviceInfoResponse& from);

  inline DeviceInfoResponse& operator=(const DeviceInfoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeviceInfoResponse(DeviceInfoResponse&& from) noexcept
    : DeviceInfoResponse() {
    *this = ::std::move(from);
  }

  inline DeviceInfoResponse& operator=(DeviceInfoResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeviceInfoResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeviceInfoResponse* internal_default_instance() {
    return reinterpret_cast<const DeviceInfoResponse*>(
               &_DeviceInfoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(DeviceInfoResponse* other);
  friend void swap(DeviceInfoResponse& a, DeviceInfoResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeviceInfoResponse* New() const final {
    return CreateMaybeMessage<DeviceInfoResponse>(NULL);
  }

  DeviceInfoResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeviceInfoResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DeviceInfoResponse& from);
  void MergeFrom(const DeviceInfoResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeviceInfoResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .device_service.DeviceInfoDetail info = 1;
  bool has_info() const;
  void clear_info();
  static const int kInfoFieldNumber = 1;
  private:
  const ::device_service::DeviceInfoDetail& _internal_info() const;
  public:
  const ::device_service::DeviceInfoDetail& info() const;
  ::device_service::DeviceInfoDetail* release_info();
  ::device_service::DeviceInfoDetail* mutable_info();
  void set_allocated_info(::device_service::DeviceInfoDetail* info);

  // @@protoc_insertion_point(class_scope:device_service.DeviceInfoResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::device_service::DeviceInfoDetail* info_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_device_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeviceTableBySlaveIdRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:device_service.DeviceTableBySlaveIdRequest) */ {
 public:
  DeviceTableBySlaveIdRequest();
  virtual ~DeviceTableBySlaveIdRequest();

  DeviceTableBySlaveIdRequest(const DeviceTableBySlaveIdRequest& from);

  inline DeviceTableBySlaveIdRequest& operator=(const DeviceTableBySlaveIdRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeviceTableBySlaveIdRequest(DeviceTableBySlaveIdRequest&& from) noexcept
    : DeviceTableBySlaveIdRequest() {
    *this = ::std::move(from);
  }

  inline DeviceTableBySlaveIdRequest& operator=(DeviceTableBySlaveIdRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeviceTableBySlaveIdRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeviceTableBySlaveIdRequest* internal_default_instance() {
    return reinterpret_cast<const DeviceTableBySlaveIdRequest*>(
               &_DeviceTableBySlaveIdRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(DeviceTableBySlaveIdRequest* other);
  friend void swap(DeviceTableBySlaveIdRequest& a, DeviceTableBySlaveIdRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeviceTableBySlaveIdRequest* New() const final {
    return CreateMaybeMessage<DeviceTableBySlaveIdRequest>(NULL);
  }

  DeviceTableBySlaveIdRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeviceTableBySlaveIdRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DeviceTableBySlaveIdRequest& from);
  void MergeFrom(const DeviceTableBySlaveIdRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeviceTableBySlaveIdRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string device_name = 1;
  void clear_device_name();
  static const int kDeviceNameFieldNumber = 1;
  const ::std::string& device_name() const;
  void set_device_name(const ::std::string& value);
  #if LANG_CXX11
  void set_device_name(::std::string&& value);
  #endif
  void set_device_name(const char* value);
  void set_device_name(const char* value, size_t size);
  ::std::string* mutable_device_name();
  ::std::string* release_device_name();
  void set_allocated_device_name(::std::string* device_name);

  // string point_name = 3;
  void clear_point_name();
  static const int kPointNameFieldNumber = 3;
  const ::std::string& point_name() const;
  void set_point_name(const ::std::string& value);
  #if LANG_CXX11
  void set_point_name(::std::string&& value);
  #endif
  void set_point_name(const char* value);
  void set_point_name(const char* value, size_t size);
  ::std::string* mutable_point_name();
  ::std::string* release_point_name();
  void set_allocated_point_name(::std::string* point_name);

  // int32 slave_id = 2;
  void clear_slave_id();
  static const int kSlaveIdFieldNumber = 2;
  ::google::protobuf::int32 slave_id() const;
  void set_slave_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:device_service.DeviceTableBySlaveIdRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr device_name_;
  ::google::protobuf::internal::ArenaStringPtr point_name_;
  ::google::protobuf::int32 slave_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_device_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeviceTableRow : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:device_service.DeviceTableRow) */ {
 public:
  DeviceTableRow();
  virtual ~DeviceTableRow();

  DeviceTableRow(const DeviceTableRow& from);

  inline DeviceTableRow& operator=(const DeviceTableRow& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeviceTableRow(DeviceTableRow&& from) noexcept
    : DeviceTableRow() {
    *this = ::std::move(from);
  }

  inline DeviceTableRow& operator=(DeviceTableRow&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeviceTableRow& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeviceTableRow* internal_default_instance() {
    return reinterpret_cast<const DeviceTableRow*>(
               &_DeviceTableRow_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(DeviceTableRow* other);
  friend void swap(DeviceTableRow& a, DeviceTableRow& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeviceTableRow* New() const final {
    return CreateMaybeMessage<DeviceTableRow>(NULL);
  }

  DeviceTableRow* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeviceTableRow>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DeviceTableRow& from);
  void MergeFrom(const DeviceTableRow& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeviceTableRow* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string row = 1;
  int row_size() const;
  void clear_row();
  static const int kRowFieldNumber = 1;
  const ::std::string& row(int index) const;
  ::std::string* mutable_row(int index);
  void set_row(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_row(int index, ::std::string&& value);
  #endif
  void set_row(int index, const char* value);
  void set_row(int index, const char* value, size_t size);
  ::std::string* add_row();
  void add_row(const ::std::string& value);
  #if LANG_CXX11
  void add_row(::std::string&& value);
  #endif
  void add_row(const char* value);
  void add_row(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& row() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_row();

  // @@protoc_insertion_point(class_scope:device_service.DeviceTableRow)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> row_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_device_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeviceTableBySlaveIdResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:device_service.DeviceTableBySlaveIdResponse) */ {
 public:
  DeviceTableBySlaveIdResponse();
  virtual ~DeviceTableBySlaveIdResponse();

  DeviceTableBySlaveIdResponse(const DeviceTableBySlaveIdResponse& from);

  inline DeviceTableBySlaveIdResponse& operator=(const DeviceTableBySlaveIdResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeviceTableBySlaveIdResponse(DeviceTableBySlaveIdResponse&& from) noexcept
    : DeviceTableBySlaveIdResponse() {
    *this = ::std::move(from);
  }

  inline DeviceTableBySlaveIdResponse& operator=(DeviceTableBySlaveIdResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeviceTableBySlaveIdResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeviceTableBySlaveIdResponse* internal_default_instance() {
    return reinterpret_cast<const DeviceTableBySlaveIdResponse*>(
               &_DeviceTableBySlaveIdResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  void Swap(DeviceTableBySlaveIdResponse* other);
  friend void swap(DeviceTableBySlaveIdResponse& a, DeviceTableBySlaveIdResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeviceTableBySlaveIdResponse* New() const final {
    return CreateMaybeMessage<DeviceTableBySlaveIdResponse>(NULL);
  }

  DeviceTableBySlaveIdResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeviceTableBySlaveIdResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DeviceTableBySlaveIdResponse& from);
  void MergeFrom(const DeviceTableBySlaveIdResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeviceTableBySlaveIdResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .device_service.DeviceTableRow table_data = 2;
  int table_data_size() const;
  void clear_table_data();
  static const int kTableDataFieldNumber = 2;
  ::device_service::DeviceTableRow* mutable_table_data(int index);
  ::google::protobuf::RepeatedPtrField< ::device_service::DeviceTableRow >*
      mutable_table_data();
  const ::device_service::DeviceTableRow& table_data(int index) const;
  ::device_service::DeviceTableRow* add_table_data();
  const ::google::protobuf::RepeatedPtrField< ::device_service::DeviceTableRow >&
      table_data() const;

  // .device_service.DeviceTableRow head_data = 1;
  bool has_head_data() const;
  void clear_head_data();
  static const int kHeadDataFieldNumber = 1;
  private:
  const ::device_service::DeviceTableRow& _internal_head_data() const;
  public:
  const ::device_service::DeviceTableRow& head_data() const;
  ::device_service::DeviceTableRow* release_head_data();
  ::device_service::DeviceTableRow* mutable_head_data();
  void set_allocated_head_data(::device_service::DeviceTableRow* head_data);

  // @@protoc_insertion_point(class_scope:device_service.DeviceTableBySlaveIdResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::device_service::DeviceTableRow > table_data_;
  ::device_service::DeviceTableRow* head_data_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_device_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DeviceNameListRequest

// string device_name = 1;
inline void DeviceNameListRequest::clear_device_name() {
  device_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DeviceNameListRequest::device_name() const {
  // @@protoc_insertion_point(field_get:device_service.DeviceNameListRequest.device_name)
  return device_name_.GetNoArena();
}
inline void DeviceNameListRequest::set_device_name(const ::std::string& value) {
  
  device_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:device_service.DeviceNameListRequest.device_name)
}
#if LANG_CXX11
inline void DeviceNameListRequest::set_device_name(::std::string&& value) {
  
  device_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:device_service.DeviceNameListRequest.device_name)
}
#endif
inline void DeviceNameListRequest::set_device_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  device_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:device_service.DeviceNameListRequest.device_name)
}
inline void DeviceNameListRequest::set_device_name(const char* value, size_t size) {
  
  device_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:device_service.DeviceNameListRequest.device_name)
}
inline ::std::string* DeviceNameListRequest::mutable_device_name() {
  
  // @@protoc_insertion_point(field_mutable:device_service.DeviceNameListRequest.device_name)
  return device_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeviceNameListRequest::release_device_name() {
  // @@protoc_insertion_point(field_release:device_service.DeviceNameListRequest.device_name)
  
  return device_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeviceNameListRequest::set_allocated_device_name(::std::string* device_name) {
  if (device_name != NULL) {
    
  } else {
    
  }
  device_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_name);
  // @@protoc_insertion_point(field_set_allocated:device_service.DeviceNameListRequest.device_name)
}

// -------------------------------------------------------------------

// DeviceNameListResponse

// repeated string device_names = 1;
inline int DeviceNameListResponse::device_names_size() const {
  return device_names_.size();
}
inline void DeviceNameListResponse::clear_device_names() {
  device_names_.Clear();
}
inline const ::std::string& DeviceNameListResponse::device_names(int index) const {
  // @@protoc_insertion_point(field_get:device_service.DeviceNameListResponse.device_names)
  return device_names_.Get(index);
}
inline ::std::string* DeviceNameListResponse::mutable_device_names(int index) {
  // @@protoc_insertion_point(field_mutable:device_service.DeviceNameListResponse.device_names)
  return device_names_.Mutable(index);
}
inline void DeviceNameListResponse::set_device_names(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:device_service.DeviceNameListResponse.device_names)
  device_names_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void DeviceNameListResponse::set_device_names(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:device_service.DeviceNameListResponse.device_names)
  device_names_.Mutable(index)->assign(std::move(value));
}
#endif
inline void DeviceNameListResponse::set_device_names(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  device_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:device_service.DeviceNameListResponse.device_names)
}
inline void DeviceNameListResponse::set_device_names(int index, const char* value, size_t size) {
  device_names_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:device_service.DeviceNameListResponse.device_names)
}
inline ::std::string* DeviceNameListResponse::add_device_names() {
  // @@protoc_insertion_point(field_add_mutable:device_service.DeviceNameListResponse.device_names)
  return device_names_.Add();
}
inline void DeviceNameListResponse::add_device_names(const ::std::string& value) {
  device_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:device_service.DeviceNameListResponse.device_names)
}
#if LANG_CXX11
inline void DeviceNameListResponse::add_device_names(::std::string&& value) {
  device_names_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:device_service.DeviceNameListResponse.device_names)
}
#endif
inline void DeviceNameListResponse::add_device_names(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  device_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:device_service.DeviceNameListResponse.device_names)
}
inline void DeviceNameListResponse::add_device_names(const char* value, size_t size) {
  device_names_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:device_service.DeviceNameListResponse.device_names)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
DeviceNameListResponse::device_names() const {
  // @@protoc_insertion_point(field_list:device_service.DeviceNameListResponse.device_names)
  return device_names_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
DeviceNameListResponse::mutable_device_names() {
  // @@protoc_insertion_point(field_mutable_list:device_service.DeviceNameListResponse.device_names)
  return &device_names_;
}

// -------------------------------------------------------------------

// DeviceSlaveCntRequest

// string device_name = 1;
inline void DeviceSlaveCntRequest::clear_device_name() {
  device_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DeviceSlaveCntRequest::device_name() const {
  // @@protoc_insertion_point(field_get:device_service.DeviceSlaveCntRequest.device_name)
  return device_name_.GetNoArena();
}
inline void DeviceSlaveCntRequest::set_device_name(const ::std::string& value) {
  
  device_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:device_service.DeviceSlaveCntRequest.device_name)
}
#if LANG_CXX11
inline void DeviceSlaveCntRequest::set_device_name(::std::string&& value) {
  
  device_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:device_service.DeviceSlaveCntRequest.device_name)
}
#endif
inline void DeviceSlaveCntRequest::set_device_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  device_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:device_service.DeviceSlaveCntRequest.device_name)
}
inline void DeviceSlaveCntRequest::set_device_name(const char* value, size_t size) {
  
  device_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:device_service.DeviceSlaveCntRequest.device_name)
}
inline ::std::string* DeviceSlaveCntRequest::mutable_device_name() {
  
  // @@protoc_insertion_point(field_mutable:device_service.DeviceSlaveCntRequest.device_name)
  return device_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeviceSlaveCntRequest::release_device_name() {
  // @@protoc_insertion_point(field_release:device_service.DeviceSlaveCntRequest.device_name)
  
  return device_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeviceSlaveCntRequest::set_allocated_device_name(::std::string* device_name) {
  if (device_name != NULL) {
    
  } else {
    
  }
  device_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_name);
  // @@protoc_insertion_point(field_set_allocated:device_service.DeviceSlaveCntRequest.device_name)
}

// -------------------------------------------------------------------

// DeviceSlaveCntResponse

// int32 slave_cnt = 1;
inline void DeviceSlaveCntResponse::clear_slave_cnt() {
  slave_cnt_ = 0;
}
inline ::google::protobuf::int32 DeviceSlaveCntResponse::slave_cnt() const {
  // @@protoc_insertion_point(field_get:device_service.DeviceSlaveCntResponse.slave_cnt)
  return slave_cnt_;
}
inline void DeviceSlaveCntResponse::set_slave_cnt(::google::protobuf::int32 value) {
  
  slave_cnt_ = value;
  // @@protoc_insertion_point(field_set:device_service.DeviceSlaveCntResponse.slave_cnt)
}

// -------------------------------------------------------------------

// DeviceInfoDetail

// string ip = 1;
inline void DeviceInfoDetail::clear_ip() {
  ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DeviceInfoDetail::ip() const {
  // @@protoc_insertion_point(field_get:device_service.DeviceInfoDetail.ip)
  return ip_.GetNoArena();
}
inline void DeviceInfoDetail::set_ip(const ::std::string& value) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:device_service.DeviceInfoDetail.ip)
}
#if LANG_CXX11
inline void DeviceInfoDetail::set_ip(::std::string&& value) {
  
  ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:device_service.DeviceInfoDetail.ip)
}
#endif
inline void DeviceInfoDetail::set_ip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:device_service.DeviceInfoDetail.ip)
}
inline void DeviceInfoDetail::set_ip(const char* value, size_t size) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:device_service.DeviceInfoDetail.ip)
}
inline ::std::string* DeviceInfoDetail::mutable_ip() {
  
  // @@protoc_insertion_point(field_mutable:device_service.DeviceInfoDetail.ip)
  return ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeviceInfoDetail::release_ip() {
  // @@protoc_insertion_point(field_release:device_service.DeviceInfoDetail.ip)
  
  return ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeviceInfoDetail::set_allocated_ip(::std::string* ip) {
  if (ip != NULL) {
    
  } else {
    
  }
  ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ip);
  // @@protoc_insertion_point(field_set_allocated:device_service.DeviceInfoDetail.ip)
}

// int32 port = 2;
inline void DeviceInfoDetail::clear_port() {
  port_ = 0;
}
inline ::google::protobuf::int32 DeviceInfoDetail::port() const {
  // @@protoc_insertion_point(field_get:device_service.DeviceInfoDetail.port)
  return port_;
}
inline void DeviceInfoDetail::set_port(::google::protobuf::int32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:device_service.DeviceInfoDetail.port)
}

// string type = 3;
inline void DeviceInfoDetail::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DeviceInfoDetail::type() const {
  // @@protoc_insertion_point(field_get:device_service.DeviceInfoDetail.type)
  return type_.GetNoArena();
}
inline void DeviceInfoDetail::set_type(const ::std::string& value) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:device_service.DeviceInfoDetail.type)
}
#if LANG_CXX11
inline void DeviceInfoDetail::set_type(::std::string&& value) {
  
  type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:device_service.DeviceInfoDetail.type)
}
#endif
inline void DeviceInfoDetail::set_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:device_service.DeviceInfoDetail.type)
}
inline void DeviceInfoDetail::set_type(const char* value, size_t size) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:device_service.DeviceInfoDetail.type)
}
inline ::std::string* DeviceInfoDetail::mutable_type() {
  
  // @@protoc_insertion_point(field_mutable:device_service.DeviceInfoDetail.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeviceInfoDetail::release_type() {
  // @@protoc_insertion_point(field_release:device_service.DeviceInfoDetail.type)
  
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeviceInfoDetail::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    
  } else {
    
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:device_service.DeviceInfoDetail.type)
}

// bool server_status = 4;
inline void DeviceInfoDetail::clear_server_status() {
  server_status_ = false;
}
inline bool DeviceInfoDetail::server_status() const {
  // @@protoc_insertion_point(field_get:device_service.DeviceInfoDetail.server_status)
  return server_status_;
}
inline void DeviceInfoDetail::set_server_status(bool value) {
  
  server_status_ = value;
  // @@protoc_insertion_point(field_set:device_service.DeviceInfoDetail.server_status)
}

// bool simulate_status = 5;
inline void DeviceInfoDetail::clear_simulate_status() {
  simulate_status_ = false;
}
inline bool DeviceInfoDetail::simulate_status() const {
  // @@protoc_insertion_point(field_get:device_service.DeviceInfoDetail.simulate_status)
  return simulate_status_;
}
inline void DeviceInfoDetail::set_simulate_status(bool value) {
  
  simulate_status_ = value;
  // @@protoc_insertion_point(field_set:device_service.DeviceInfoDetail.simulate_status)
}

// bool plan_status = 6;
inline void DeviceInfoDetail::clear_plan_status() {
  plan_status_ = false;
}
inline bool DeviceInfoDetail::plan_status() const {
  // @@protoc_insertion_point(field_get:device_service.DeviceInfoDetail.plan_status)
  return plan_status_;
}
inline void DeviceInfoDetail::set_plan_status(bool value) {
  
  plan_status_ = value;
  // @@protoc_insertion_point(field_set:device_service.DeviceInfoDetail.plan_status)
}

// -------------------------------------------------------------------

// DeviceInfoRequest

// string device_name = 1;
inline void DeviceInfoRequest::clear_device_name() {
  device_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DeviceInfoRequest::device_name() const {
  // @@protoc_insertion_point(field_get:device_service.DeviceInfoRequest.device_name)
  return device_name_.GetNoArena();
}
inline void DeviceInfoRequest::set_device_name(const ::std::string& value) {
  
  device_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:device_service.DeviceInfoRequest.device_name)
}
#if LANG_CXX11
inline void DeviceInfoRequest::set_device_name(::std::string&& value) {
  
  device_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:device_service.DeviceInfoRequest.device_name)
}
#endif
inline void DeviceInfoRequest::set_device_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  device_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:device_service.DeviceInfoRequest.device_name)
}
inline void DeviceInfoRequest::set_device_name(const char* value, size_t size) {
  
  device_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:device_service.DeviceInfoRequest.device_name)
}
inline ::std::string* DeviceInfoRequest::mutable_device_name() {
  
  // @@protoc_insertion_point(field_mutable:device_service.DeviceInfoRequest.device_name)
  return device_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeviceInfoRequest::release_device_name() {
  // @@protoc_insertion_point(field_release:device_service.DeviceInfoRequest.device_name)
  
  return device_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeviceInfoRequest::set_allocated_device_name(::std::string* device_name) {
  if (device_name != NULL) {
    
  } else {
    
  }
  device_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_name);
  // @@protoc_insertion_point(field_set_allocated:device_service.DeviceInfoRequest.device_name)
}

// -------------------------------------------------------------------

// DeviceInfoResponse

// .device_service.DeviceInfoDetail info = 1;
inline bool DeviceInfoResponse::has_info() const {
  return this != internal_default_instance() && info_ != NULL;
}
inline void DeviceInfoResponse::clear_info() {
  if (GetArenaNoVirtual() == NULL && info_ != NULL) {
    delete info_;
  }
  info_ = NULL;
}
inline const ::device_service::DeviceInfoDetail& DeviceInfoResponse::_internal_info() const {
  return *info_;
}
inline const ::device_service::DeviceInfoDetail& DeviceInfoResponse::info() const {
  const ::device_service::DeviceInfoDetail* p = info_;
  // @@protoc_insertion_point(field_get:device_service.DeviceInfoResponse.info)
  return p != NULL ? *p : *reinterpret_cast<const ::device_service::DeviceInfoDetail*>(
      &::device_service::_DeviceInfoDetail_default_instance_);
}
inline ::device_service::DeviceInfoDetail* DeviceInfoResponse::release_info() {
  // @@protoc_insertion_point(field_release:device_service.DeviceInfoResponse.info)
  
  ::device_service::DeviceInfoDetail* temp = info_;
  info_ = NULL;
  return temp;
}
inline ::device_service::DeviceInfoDetail* DeviceInfoResponse::mutable_info() {
  
  if (info_ == NULL) {
    auto* p = CreateMaybeMessage<::device_service::DeviceInfoDetail>(GetArenaNoVirtual());
    info_ = p;
  }
  // @@protoc_insertion_point(field_mutable:device_service.DeviceInfoResponse.info)
  return info_;
}
inline void DeviceInfoResponse::set_allocated_info(::device_service::DeviceInfoDetail* info) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete info_;
  }
  if (info) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      info = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, info, submessage_arena);
    }
    
  } else {
    
  }
  info_ = info;
  // @@protoc_insertion_point(field_set_allocated:device_service.DeviceInfoResponse.info)
}

// -------------------------------------------------------------------

// DeviceTableBySlaveIdRequest

// string device_name = 1;
inline void DeviceTableBySlaveIdRequest::clear_device_name() {
  device_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DeviceTableBySlaveIdRequest::device_name() const {
  // @@protoc_insertion_point(field_get:device_service.DeviceTableBySlaveIdRequest.device_name)
  return device_name_.GetNoArena();
}
inline void DeviceTableBySlaveIdRequest::set_device_name(const ::std::string& value) {
  
  device_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:device_service.DeviceTableBySlaveIdRequest.device_name)
}
#if LANG_CXX11
inline void DeviceTableBySlaveIdRequest::set_device_name(::std::string&& value) {
  
  device_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:device_service.DeviceTableBySlaveIdRequest.device_name)
}
#endif
inline void DeviceTableBySlaveIdRequest::set_device_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  device_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:device_service.DeviceTableBySlaveIdRequest.device_name)
}
inline void DeviceTableBySlaveIdRequest::set_device_name(const char* value, size_t size) {
  
  device_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:device_service.DeviceTableBySlaveIdRequest.device_name)
}
inline ::std::string* DeviceTableBySlaveIdRequest::mutable_device_name() {
  
  // @@protoc_insertion_point(field_mutable:device_service.DeviceTableBySlaveIdRequest.device_name)
  return device_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeviceTableBySlaveIdRequest::release_device_name() {
  // @@protoc_insertion_point(field_release:device_service.DeviceTableBySlaveIdRequest.device_name)
  
  return device_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeviceTableBySlaveIdRequest::set_allocated_device_name(::std::string* device_name) {
  if (device_name != NULL) {
    
  } else {
    
  }
  device_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_name);
  // @@protoc_insertion_point(field_set_allocated:device_service.DeviceTableBySlaveIdRequest.device_name)
}

// int32 slave_id = 2;
inline void DeviceTableBySlaveIdRequest::clear_slave_id() {
  slave_id_ = 0;
}
inline ::google::protobuf::int32 DeviceTableBySlaveIdRequest::slave_id() const {
  // @@protoc_insertion_point(field_get:device_service.DeviceTableBySlaveIdRequest.slave_id)
  return slave_id_;
}
inline void DeviceTableBySlaveIdRequest::set_slave_id(::google::protobuf::int32 value) {
  
  slave_id_ = value;
  // @@protoc_insertion_point(field_set:device_service.DeviceTableBySlaveIdRequest.slave_id)
}

// string point_name = 3;
inline void DeviceTableBySlaveIdRequest::clear_point_name() {
  point_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DeviceTableBySlaveIdRequest::point_name() const {
  // @@protoc_insertion_point(field_get:device_service.DeviceTableBySlaveIdRequest.point_name)
  return point_name_.GetNoArena();
}
inline void DeviceTableBySlaveIdRequest::set_point_name(const ::std::string& value) {
  
  point_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:device_service.DeviceTableBySlaveIdRequest.point_name)
}
#if LANG_CXX11
inline void DeviceTableBySlaveIdRequest::set_point_name(::std::string&& value) {
  
  point_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:device_service.DeviceTableBySlaveIdRequest.point_name)
}
#endif
inline void DeviceTableBySlaveIdRequest::set_point_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  point_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:device_service.DeviceTableBySlaveIdRequest.point_name)
}
inline void DeviceTableBySlaveIdRequest::set_point_name(const char* value, size_t size) {
  
  point_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:device_service.DeviceTableBySlaveIdRequest.point_name)
}
inline ::std::string* DeviceTableBySlaveIdRequest::mutable_point_name() {
  
  // @@protoc_insertion_point(field_mutable:device_service.DeviceTableBySlaveIdRequest.point_name)
  return point_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeviceTableBySlaveIdRequest::release_point_name() {
  // @@protoc_insertion_point(field_release:device_service.DeviceTableBySlaveIdRequest.point_name)
  
  return point_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeviceTableBySlaveIdRequest::set_allocated_point_name(::std::string* point_name) {
  if (point_name != NULL) {
    
  } else {
    
  }
  point_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), point_name);
  // @@protoc_insertion_point(field_set_allocated:device_service.DeviceTableBySlaveIdRequest.point_name)
}

// -------------------------------------------------------------------

// DeviceTableRow

// repeated string row = 1;
inline int DeviceTableRow::row_size() const {
  return row_.size();
}
inline void DeviceTableRow::clear_row() {
  row_.Clear();
}
inline const ::std::string& DeviceTableRow::row(int index) const {
  // @@protoc_insertion_point(field_get:device_service.DeviceTableRow.row)
  return row_.Get(index);
}
inline ::std::string* DeviceTableRow::mutable_row(int index) {
  // @@protoc_insertion_point(field_mutable:device_service.DeviceTableRow.row)
  return row_.Mutable(index);
}
inline void DeviceTableRow::set_row(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:device_service.DeviceTableRow.row)
  row_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void DeviceTableRow::set_row(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:device_service.DeviceTableRow.row)
  row_.Mutable(index)->assign(std::move(value));
}
#endif
inline void DeviceTableRow::set_row(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  row_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:device_service.DeviceTableRow.row)
}
inline void DeviceTableRow::set_row(int index, const char* value, size_t size) {
  row_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:device_service.DeviceTableRow.row)
}
inline ::std::string* DeviceTableRow::add_row() {
  // @@protoc_insertion_point(field_add_mutable:device_service.DeviceTableRow.row)
  return row_.Add();
}
inline void DeviceTableRow::add_row(const ::std::string& value) {
  row_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:device_service.DeviceTableRow.row)
}
#if LANG_CXX11
inline void DeviceTableRow::add_row(::std::string&& value) {
  row_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:device_service.DeviceTableRow.row)
}
#endif
inline void DeviceTableRow::add_row(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  row_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:device_service.DeviceTableRow.row)
}
inline void DeviceTableRow::add_row(const char* value, size_t size) {
  row_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:device_service.DeviceTableRow.row)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
DeviceTableRow::row() const {
  // @@protoc_insertion_point(field_list:device_service.DeviceTableRow.row)
  return row_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
DeviceTableRow::mutable_row() {
  // @@protoc_insertion_point(field_mutable_list:device_service.DeviceTableRow.row)
  return &row_;
}

// -------------------------------------------------------------------

// DeviceTableBySlaveIdResponse

// .device_service.DeviceTableRow head_data = 1;
inline bool DeviceTableBySlaveIdResponse::has_head_data() const {
  return this != internal_default_instance() && head_data_ != NULL;
}
inline void DeviceTableBySlaveIdResponse::clear_head_data() {
  if (GetArenaNoVirtual() == NULL && head_data_ != NULL) {
    delete head_data_;
  }
  head_data_ = NULL;
}
inline const ::device_service::DeviceTableRow& DeviceTableBySlaveIdResponse::_internal_head_data() const {
  return *head_data_;
}
inline const ::device_service::DeviceTableRow& DeviceTableBySlaveIdResponse::head_data() const {
  const ::device_service::DeviceTableRow* p = head_data_;
  // @@protoc_insertion_point(field_get:device_service.DeviceTableBySlaveIdResponse.head_data)
  return p != NULL ? *p : *reinterpret_cast<const ::device_service::DeviceTableRow*>(
      &::device_service::_DeviceTableRow_default_instance_);
}
inline ::device_service::DeviceTableRow* DeviceTableBySlaveIdResponse::release_head_data() {
  // @@protoc_insertion_point(field_release:device_service.DeviceTableBySlaveIdResponse.head_data)
  
  ::device_service::DeviceTableRow* temp = head_data_;
  head_data_ = NULL;
  return temp;
}
inline ::device_service::DeviceTableRow* DeviceTableBySlaveIdResponse::mutable_head_data() {
  
  if (head_data_ == NULL) {
    auto* p = CreateMaybeMessage<::device_service::DeviceTableRow>(GetArenaNoVirtual());
    head_data_ = p;
  }
  // @@protoc_insertion_point(field_mutable:device_service.DeviceTableBySlaveIdResponse.head_data)
  return head_data_;
}
inline void DeviceTableBySlaveIdResponse::set_allocated_head_data(::device_service::DeviceTableRow* head_data) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete head_data_;
  }
  if (head_data) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      head_data = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, head_data, submessage_arena);
    }
    
  } else {
    
  }
  head_data_ = head_data;
  // @@protoc_insertion_point(field_set_allocated:device_service.DeviceTableBySlaveIdResponse.head_data)
}

// repeated .device_service.DeviceTableRow table_data = 2;
inline int DeviceTableBySlaveIdResponse::table_data_size() const {
  return table_data_.size();
}
inline void DeviceTableBySlaveIdResponse::clear_table_data() {
  table_data_.Clear();
}
inline ::device_service::DeviceTableRow* DeviceTableBySlaveIdResponse::mutable_table_data(int index) {
  // @@protoc_insertion_point(field_mutable:device_service.DeviceTableBySlaveIdResponse.table_data)
  return table_data_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::device_service::DeviceTableRow >*
DeviceTableBySlaveIdResponse::mutable_table_data() {
  // @@protoc_insertion_point(field_mutable_list:device_service.DeviceTableBySlaveIdResponse.table_data)
  return &table_data_;
}
inline const ::device_service::DeviceTableRow& DeviceTableBySlaveIdResponse::table_data(int index) const {
  // @@protoc_insertion_point(field_get:device_service.DeviceTableBySlaveIdResponse.table_data)
  return table_data_.Get(index);
}
inline ::device_service::DeviceTableRow* DeviceTableBySlaveIdResponse::add_table_data() {
  // @@protoc_insertion_point(field_add:device_service.DeviceTableBySlaveIdResponse.table_data)
  return table_data_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::device_service::DeviceTableRow >&
DeviceTableBySlaveIdResponse::table_data() const {
  // @@protoc_insertion_point(field_list:device_service.DeviceTableBySlaveIdResponse.table_data)
  return table_data_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace device_service

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_device_2eproto
